AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FetchRootSpans:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler  # or whatever your entry file + handler is
      Runtime: nodejs22.x
      Environment:
        Variables:
          NODE_ENV: ""
          LOCALPGUSER: ""
          LOCALPGPASSWORD: ""
          LOCALPGDATABASE: ""
          LOCALPGHOST: ""
          LOCALPGPORT: ""
          PHOENIX_API_KEY: ""
          PHOENIX_API_URL: ""
      Events:
        Api:
          Type: Api
          Properties:
            Path: /fetchRootSpans
            Method: GET
