AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 300
    MemorySize: 1024  # Increase default memory to 1GB
    Environment:
      Variables:
        NODE_ENV: ""
        LOCALPGUSER: ""
        LOCALPGPASSWORD: ""
        LOCALPGDATABASE: ""
        LOCALPGHOST: ""
        LOCALPGPORT: ""
        PHOENIX_API_KEY: ""
        PHOENIX_API_URL: ""
        SPAN_INGESTION_FUNCTION_NAME: ""

Resources:
  FetchRootSpans:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ingest-root-span-worker
      Handler: dist/lambdas/ingestProject/index.handler
      MemorySize: 2048  # 2GB for span ingestion
      Events:
        Api:
          Type: Api
          Properties:
            Path: /fetchRootSpans
            Method: POST

  FetchProjects:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambdas/entry/index.handler
      MemorySize: 1536  # 1.5GB for project fetching
      Events:
        Api:
          Type: Api
          Properties:
            Path: /fetchAllProjects
            Method: GET

